### ISSUE TITLE
Issue using v2 of library

### ISSUE THREAD

**Issue by ghost** [caarlos0/gohome#9]
I copied your example code into main.go and when I try to build the app I get the following error.

```
go build
main.go:4:2: open /home/gregf/dev/go/src/github.com/gregf/thome/vendor/github.com/caarlos0/gohome/main_freebsd_test.go: no such file or directory
```

Not sure why this is happening. I used golang's dep package manager to vendor your library all the files appear to be there. Any idea what might be going on?

**Comment by ghost** [comment]
So update, I tried to use github.com/caarlos0/gohome instead of the gopkg.in link. Same error. Digged into it a bit and noticed the symlink for main_freebsd_test.go was there but the file it links to main_linux_test.go isn't there even though it's in the repo. I don't know why? Do you think this is a bug in godep?

Gopkg.lock
```
# This file is autogenerated, do not edit; changes may be undone by the next 'dep ensure'.


[[projects]]
  name = "github.com/caarlos0/gohome"
  packages = ["."]
  revision = "c08fdebe2a8b9b92637a423c66ac5d4a8f4e91e8"
  version = "v2.1.0"

[solve-meta]
  analyzer-name = "dep"
  analyzer-version = 1
  inputs-digest = "9ca54ee5464bb0e8bfb9488133cbba7d0540645fc89dbc4ecb58a52fc67c525f"
  solver-name = "gps-cdcl"
  solver-version = 1
```

**Comment by caarlos0** [comment]
seems like
